### ISSUE TITLE
No such file "ee_mumu.mad/SubProcesses/P1_epem_mupmum/Hel/selection"

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#1010]
Hi @oliviermattelaer another question, while doing some almsot final cleanup for the release.

In my tests (see #1009) I got
```
MG5_aMC>install cudacpp --local
you are using a local installer. This is intended for debugging only!
Now installing cudacpp. Be patient...
Fetching data with command:
  wget --no-check-certificate https://github.com/valassi/madgraph4gpu/releases/download/TEST_cudacpp_for3.6.0_latest/cudacpp.tar.gz
--2024-09-27 10:51:41--  https://github.com/valassi/madgraph4gpu/releases/download/TEST_cudacpp_for3.6.0_latest/cudacpp.tar.gz
...
MG5_aMC>generate e+ e- > mu+ mu-
...
MG5_aMC>output madevent_simd ee_mumu.mad --hel_recycling=False --vector_size=32 
Plugin PLUGIN.CUDACPP_OUTPUT has marked as NOT being validated with this version: 3.6.0_lo_vect. 
It has been validated for the last time with version: 3.5.2
Output will be done with PLUGIN: CUDACPP_OUTPUT
...
Compiling the bias module 'dummy'
Using random number seed offset = 21
INFO: Running Survey 
Creating Jobs
Working on SubProcesses
[Errno 2] No such file or directory: '/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/ee_mumu.mad/SubProcesses/P1_epem_mupmum/Hel/selection'
INFO:     P1_epem_mupmum  
Building madevent in madevent_interface.py with 'cpp' matrix elements
INFO:  Idle: 1,  Running: 0,  Completed: 0 [ current time: 10h52 ] 
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  0.25s  ] 
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  0.25s  ] 
INFO: End survey 
...
```

There is this line
```
[Errno 2] No such file or directory: '/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/ee_mumu.mad/SubProcesses/
```

This looks harmless as the job continues, but it does not look good.

Can/should we fix this and how?

Thanks
Andrea

**Comment by oliviermattelaer** [comment]
That's at the debug level no?
This is a notification that helicity recycling is off (so i would keep it actually)

Cheers,

Olivier

On 27 Sep 2024, at 11:10, Andrea Valassi ***@***.***> wrote:



Hi @oliviermattelaer<https://github.com/oliviermattelaer> another question, while doing some almsot final cleanup for the release.

In my tests (see #1009<https://github.com/madgraph5/madgraph4gpu/issues/1009>) I got

MG5_aMC>install cudacpp --local
you are using a local installer. This is intended for debugging only!
Now installing cudacpp. Be patient...
Fetching data with command:
  wget --no-check-certificate https://github.com/valassi/madgraph4gpu/releases/download/TEST_cudacpp_for3.6.0_latest/cudacpp.tar.gz
--2024-09-27 10:51:41--  https://github.com/valassi/madgraph4gpu/releases/download/TEST_cudacpp_for3.6.0_latest/cudacpp.tar.gz
...
MG5_aMC>generate e+ e- > mu+ mu-
...
MG5_aMC>output madevent_simd ee_mumu.mad --hel_recycling=False --vector_size=32
Plugin PLUGIN.CUDACPP_OUTPUT has marked as NOT being validated with this version: 3.6.0_lo_vect.
It has been validated for the last time with version: 3.5.2
Output will be done with PLUGIN: CUDACPP_OUTPUT
...
Compiling the bias module 'dummy'
Using random number seed offset = 21
INFO: Running Survey
Creating Jobs
Working on SubProcesses
[Errno 2] No such file or directory: '/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/ee_mumu.mad/SubProcesses/P1_epem_mupmum/Hel/selection'
INFO:     P1_epem_mupmum
Building madevent in madevent_interface.py with 'cpp' matrix elements
INFO:  Idle: 1,  Running: 0,  Completed: 0 [ current time: 10h52 ]
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  0.25s  ]
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  0.25s  ]
INFO: End survey
...


There is this line

[Errno 2] No such file or directory: '/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/ee_mumu.mad/SubProcesses/


This looks harmless as the job continues, but it does not look good.

Can/should we fix this and how?

Thanks
Andrea

**Comment by valassi** [comment]
> That's at the debug level no? This is a notification that helicity recycling is off (so i would keep it actually)

Ok no problem then! Thanks for clarifying, closing.
