### ISSUE TITLE
 Pinned host memory

### ISSUE THREAD

**Issue by roiser** [madgraph5/madgraph4gpu#13]
Tested by Peter, makes sense for > 3 iterations (still after curand on GPU?)Done also by AV: does speed up copies a lot

in Peters gitlab and eemumu_AV/master

take AV implementation - cudaMallocHost(...)

**Comment by valassi** [comment]
This is essentially done, eg in https://github.com/roiser/madgraph4gpu/blob/812f7438462c01e1052c4be48cafcdaef104195c/examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc#L189

I introdcued it here and said I was getting a factor 1.5 better throughoput. We could keep this iopen and repeat the timing test just fo rcurisoity...

https://github.com/roiser/madgraph4gpu/commit/7d27440f7ba96df9ccc728d11a1ecf18a2151ed3

**Comment by valassi** [comment]
This is done.

We might have similar/related issues in the fortran bridge, but for the SA test this is completed

Closing
