### ISSUE TITLE
 NVTX markers

### ISSUE THREAD

**Issue by roiser** [madgraph5/madgraph4gpu#14]
Done (AV)

eemumu_AV/master

**Comment by valassi** [comment]
This is essentially done in 
https://github.com/roiser/madgraph4gpu/blob/812f7438462c01e1052c4be48cafcdaef104195c/examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/timermap.h#L38

See a picture in https://indico.cern.ch/event/945769/attachments/2086317/
