### ISSUE TITLE
Allow float/double choice from 'make' (with a view on later adding float/double tests in the CI)

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#167]
This is a spinoff of issue #148 which was originally about
- fix the single precision tests in the code
- fix the single precision tests in the CI

I am about to merge a PR for the first part of the issue.

The second part remains open. It involves
- modifying headers and makefiles so that single precision builds are triggered from a -D option to make
- building an dtesting the code BOTH for float and double in the CI

PS (June 2021) This was initially "Add single precision builds and tests in the CI", it is now renamed to only include the "first part of the second part" above. The "second part of the second part" is now in #214.

**Comment by valassi** [comment]
Hi @hageboeck (and @roiser @oliviermattelaer ) I am having a look at this.

If I understand correctly, your idea was to have `make MGONGPU_CONFIG=-DMGONGPU_COMMONRAND_ONHOST` or `export MGONGPU_CONFIG=-DMGONGPU_COMMONRAND_ONHOST; make`? This is what you mentioned in the logs and in PRs #38, #59, #63.

I would like to modify a bit this logic, dropping MGONGPU_CONFIG and using individual variables. In the example above, I would suggest to modify Makefiles to allow 'make MGONGPU_COMMONRAND_ONHOST=1` or `export MGONGPU_COMMONRAND_ONHOST=1; make`.

The reason for this is that I'd like to have the float/double choice available as a separate variable, like `make MGONGPU_FPTYPE_FLOAT=1` or `export MGONGPU_FPTYPE_FLOAT=1; make`. This is what I am using for variable `AVX`.

The first main idea is that I'd like to have separate SIMULTANEOUS builds in different build directories. To achieve this (like I am doing for AVX), I need to know the choice within the Makefile, as it is the MAkefile that creates the build directories. Of course I could decrypt MGONGPU_CONFIG, but it becomes cumbersome...

The second related idea is that, in the option where no simultaneous build directoes ar eallowed, and only one is allowed, then I want to log what float/double was used, and fail the build if you start mixing different options. This is what I already do for AVX (eg make AVX=512z will fail if previously you did make AVX=avx2, without a clean in between). Same thing, I need to know the choice and it's better to get that straight than decrypt it from MGONGPU_CONFIG.

Third reason, I'd prefer avoiding the injection of arbitrary stuff into the compiler options. Presently in MGONGPUCONFIG you can inject anything and this goes straight to g++.

I am quite strong on the first two points, also to be consistent with the AVX choice (which works). I have enough of modifying FLOAT/DOUBLE by hand, cleaning and rebuilding. Even with ccache, its a nuisance to rebuild from scratch, it is easier to have simulatenous build dirs. I am less strong on the third point. If you think that for some reason you want to keep the option to inject arbitrary stuff via MGONGPUCONFIG, I would suggest to keep that by itself, but in any case I would implement the float/double in the same way as AVX, and I would also change the commonrand to do the same as AVX and float/double (ie a standalone variable, NOT related to MGONGPUCONFIG).

Any feedback? (Maybe faster to write the code than describe it, and you would understand better if I just write the code, but I wanted to check first).

Thanks
Andrea

**Comment by hageboeck** [comment]
Hi Andrea,

I understand that decrypting variables in `make` isn't fun. Go ahead.
I don't see an immediate need to inject arbitrary compiler flags. That can theoretically be done using `CXXFLAGS=xxx make` if needed, and if we need more fine-granular control for something else in the future, we'll deal with the problem when (*if*) the problem arises.

**Comment by hageboeck** [comment]
Also note that *if* we moved to cmake at some point, you would certainly go for
`cmake -DFP_BACKEND=double -D...=...`
instead of
`cmake -DGLOBAL_CONFIG="-D...DOUBLE -D...XXX"`
so one variable for one thing would anyway be the preferred solution.

**Comment by valassi** [comment]
Thanks @hageboeck for the comments. I have created PR #213 which deals with the first part of this.

I am renaming this to ONLY deal with the first part, allow extrenal choice of float/double.

The sedond part (integrating in the CI) is strpped off to #214, which remains to be done.

**Comment by valassi** [comment]
I opened a 'standing' ticket about cmake in issue #271 just to collect a few ideas realted to that. I included a link to this issue.

The external choice of float/double is however fully functional and implemented presently. In the latest epochX it applies in the same way to all processes, and is used in thr throughput scripts to save performance logs (much better than using commit logs for that). It is enough to export FPTYPE=(d|f) when running make. See https://github.com/madgraph5/madgraph4gpu/blob/e41c14202e631bb87e1f514d7d116252dfc1dac4/epochX/cudacpp/tput/throughputX.sh#L212

Integrating float tests in the CI remains open as issue #214.

Closing (but please feel free to reopen if you think it is needed...)
