### ISSUE TITLE
Physics results are unstable by adding more iterations

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#20]
See comments here 
https://github.com/roiser/madgraph4gpu/commit/7312b901f9691e38e6eb7984d3e6c44e6995a32b

```
time ./gcheck.exe -p 16384 32 12
***************************************
NumIterations             = 12
NumThreadsPerBlock        = 32
NumBlocksPerGrid          = 16384
---------------------------------------
FP precision              = DOUBLE (nan=0)
Complex type              = THRUST::COMPLEX
Momenta memory layout     = AOSOA[32]
Wavefunction GPU memory   = LOCAL
Curand generation         = DEVICE (CUDA code)
---------------------------------------
NumMatrixElementsComputed = 6291456
MatrixElementsPerSec      = 5.107595e+08 sec^-1
***************************************
NumMatrixElements(notNan) = 6291456
MeanMatrixElemValue       = 1.394735e-02 GeV^0
StdErrMatrixElemValue     = 3.034488e-06 GeV^0
StdDevMatrixElemValue     = 7.611337e-03 GeV^0
MinMatrixElemValue        = 6.071582e-03 GeV^0
MaxMatrixElemValue        = 3.374925e-02 GeV^0
***************************************

time ./gcheck.exe -p 16384 32 120
***************************************
NumIterations             = 120
NumThreadsPerBlock        = 32
NumBlocksPerGrid          = 16384
---------------------------------------
FP precision              = DOUBLE (nan=0)
Complex type              = THRUST::COMPLEX
Momenta memory layout     = AOSOA[32]
Wavefunction GPU memory   = LOCAL
Curand generation         = DEVICE (CUDA code)
---------------------------------------
NumMatrixElementsComputed = 62914560
MatrixElementsPerSec      = 5.386196e+08 sec^-1
***************************************
NumMatrixElements(notNan) = 62914560
MeanMatrixElemValue       = 9.014087e-03 GeV^0
StdErrMatrixElemValue     = 1.444561e-06 GeV^0
StdDevMatrixElemValue     = 1.145807e-02 GeV^0
MinMatrixElemValue        = 6.071582e-03 GeV^0
MaxMatrixElemValue        = 3.374925e-02 GeV^0
***************************************
```

The mean ME was 1.4E-2 with 12 iterations and becomes 0.9E-2 with 120. The standard error (the precision on the estimate of this mean) is of the ordere of 3E-6, so results should be MUCH more stable. 

Also the standard deviation (the width of the ME distribution) was 8E-3 and becomes 11E-3. There is clearly something wrong. 

Todo: 
- should check whether something similar was also happening with the in-house random numbers, or whether it was introduced with the switch to curand
- should print out the average ME and stddev on ME for EACH iteration

**Comment by valassi** [comment]
Fixed here: https://github.com/madgraph5/madgraph4gpu/commit/6430986910e97e1a9aef05bc6e1cb522c4bedb90

It was very simple, with millions of MEs, we need double and not float to do the rolling sum...

En passant I tested several other random number generators, which on the GPU are faster than on the CPU.

Fixed and closed.

**Comment by roiser** [comment]
Maybe related, @TaranSinghania just tried to run the code on a consumer card and fails, the card has no double precision units.

**Comment by valassi** [comment]
Hi Stefan, no, I doubt it. This issue #20 was about the use of float instead of double on the host-side code doing the final ME average. If Taran has an issue, the bext is to try the MGONGPU_FPTYPE_FLOAT switch. Note that doubles will in any case be used to solve this issue #20 (the double is hardcoded, just like the float was previously hardcoded - it does not use the fptype typedef that can switcvh from one to the opther)

**Comment by roiser** [comment]
Yes, I think that's correct. Taran has done the switch, still the code doesn't work (with some spurious assert which doesn't mean a lot). I guess we should get access to some consumer card to try this ourselves. I close this again. Thanks for confirming.

**Comment by valassi** [comment]
Interesting. Then yes maybe we should ask Ricardo to also have one consumer card, in addition to the three V100
