### ISSUE TITLE
Add single precision builds and tests in the CI 

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#214]
This is the second part of #167, which initially had this name but actually had two parts
- Modify Makefiles and headers to allow external choice of float/double: this is now only in #167 and is done by #213
- Based on the above, modify the github CI infrestaruture

**Comment by valassi** [comment]
@hageboeck you want to do this? I would start with eemumu only (wherethe above is done).
 
About ggtgg that requires much more work (not only porting #213, but also porting various fixes to the tests from other PRs, and possibly additional fixes in the c++/cuda), before the CI stage.

Thanks Andrea

**Comment by hageboeck** [comment]
I'll have a look on how to activate a build & test for eemumu. I understand that for gg, it's better to wait?

**Comment by valassi** [comment]
> 
> 
> I'll have a look on how to activate a build & test for eemumu. I understand that for gg, it's better to wait?

Thanks! Yes just wait for gg*... see some comments in #213

**Comment by hageboeck** [comment]
- [x] eemumu is addressed in #217.
- [ ] gg* to be done.

**Comment by hageboeck** [comment]
Reopening (github closed it), since gg* is missing.

**Comment by valassi** [comment]
Reviewing old issues... @hageboeck I am tempted to close this. I think the real need was to have AT LEAST ONE float build for both c++ and cuda in the CI. I am not sure we need to have every single process there (and even, we are testing epochX cudacpp there, it would instead be interestung to add at least one sycl/kokkos/alpaka eventually).

This is to say: I do not think we also need ggtt and ggttgg float from epochX/cudacpp in the CI. But then, as you prefer.

Thanks!
Andrea

**Comment by hageboeck** [comment]
Less CI jobs are of course better as long as we cover all code paths. 👍

**Comment by valassi** [comment]
Hi @hageboeck thanks again for this. I am closing this. In the meantime we have also added mixed precision to the CI (see #580, #581, MR #582).

This can beclosed.
