### ISSUE TITLE
Work needed towards a full workflow usable by experiments

### ISSUE THREAD

**Issue by roiser** [madgraph5/madgraph4gpu#255]
Opening an issue to describe what is needed for producing a workflow that could potentially be used by experiments to run Madgraph with the developments done for GPU acceleration and CPU vectorized code. 

Architecturally the matrix element calculation code developed in C++ and for GPUs will replace the corresponding code in the already existing production grade Fortran implementation for MG5. Looking at a rough division of the workflow, the other parts of the sequence (random number generation, phase space sampling, MC integration, unweighting, etc.) will stay in Fortran and the main executable will be also in Fortran. In order to complete this work the following needs to be achieved

1. Call C++ from within Fortran and pass the necessary input parameters
2. Transpose input arrays from Fortran column-major to C++ row-major order
3. Integrate the ME calculation code into the new workflow (needs some re-organisation, e.g. code from the old main)
4. Implement more missing functionality in C++/GPU that was not part of the so-far RAMBO based code
5. Transpose the output again and pass back to Fortran for remaining steps. 

Steps 1. and 2. have been worked on in #248

**Comment by valassi** [comment]
Hi @roiser, an update version of this issue is in my #576plan towards an alpha release. I am closing this.
