### ISSUE TITLE
EpochX sycl fails to build when using -ffast-math

### ISSUE THREAD

**Issue by lfield** [madgraph5/madgraph4gpu#259]
` clang++ -v -pthread -ffast-math -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice --cuda-include-ptx=sm_70 -fsycl-unnamed-lambda --cuda-path=/usr/local/cuda-10.2/ -I src -I SubProcesses/P1_Sigma_sm_gg_ttxgg/ SubProcesses/P1_Sigma_sm_gg_ttxgg/CPPProcess.cc src/rambo.cc src/read_slha.cc src/Parameters_sm.cc SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc -I ../../../tools/ -o SubProcesses/P1_Sigma_sm_gg_ttxgg/gcheck_sa.exe`

 "/usr/local/cuda-10.2//bin/ptxas" -m64 -O0 -v --gpu-name sm_50 --output-file /tmp/CPPProcess-c26270.o /tmp/CPPProcess-5d138c.s
ptxas fatal   : Unresolved extern function '__sqrt_finite'

**Comment by nscottnichols** [comment]
I'm pretty sure it's version 2.31 on both machines I've tested on. I checked using `ldd --version`.

**Comment by lfield** [comment]
Fixed with PR #293

**Comment by lfield** [comment]
For information https://github.com/intel/llvm/issues
