### ISSUE TITLE
EpochX sycl CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by lfield** [madgraph5/madgraph4gpu#262]
The program runs fie when using  `./gcheck_sa.exe 1 8 1` but fails when using  `./gcheck_sa.exe 1 16 1`

Selected Tesla V100S-PCIE-32GB on platform NVIDIA CUDA BACKEND

PI CUDA ERROR:
	Value:           700
	Name:            CUDA_ERROR_ILLEGAL_ADDRESS
	Description:     an illegal memory access was encountered
	Function:        wait
	Source Location: /root/sycl_workspace/llvm/sycl/plugins/cuda/pi_cuda.cpp:427

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
Aborted (core dumped)

**Comment by nscottnichols** [comment]
I finally fixed the toolchain issue and am having the same issue on an A100. I've been thinking about switching USM vs the buffer/accessor method and maybe we could see some benefit there. Also, I'm not having this issue on my local machine's Intel gpu, cpu, or emulated FPGA.

Selected A100-SXM4-40GB on platform NVIDIA CUDA BACKENDPI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        cuda_piQueueFinish
        Source Location: /home/nscottnichols/sycl_workspace/llvm/sycl/plugins/cuda/pi_cuda.cpp:2215

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  Native API failed. Native API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
