### ISSUE TITLE
Sycl code returns nan

### ISSUE THREAD

**Issue by lfield** [madgraph5/madgraph4gpu#294]
The sycl code is returning nan
```
NumMatrixElements(notNan)  = 0
MeanMatrixElemValue        = ( nan +- -nan )  GeV^-4
[Min,Max]MatrixElemValue   = [ nan ,  nan ]  GeV^-4
StdDevMatrixElemValue      = ( -nan                 )  GeV^-4
MeanWeight                 = ( -nan +- -nan )
[Min,Max]Weight            = [ 2.812272e+01 ,  2.812272e+01 ]
StdDevWeight               = ( -nan                 )
```

**Comment by valassi** [comment]
Note that fast math may need to be disabled in the calling sequence. If the ME calculation returns a "problematic" ME, this must be excluded from all sums and averages. Determining if a value is NaN is not straightforward if you use fast math. I added some layer of logic to do that, see for instance https://github.com/madgraph5/madgraph4gpu/blob/2a416d4f01cc9c8809a139fe60b610213990a333/epochX/cudacpp/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc#L47

**Comment by lfield** [comment]
Thanks. This also happens when not using fast math so might be another problem.
