### ISSUE TITLE
Interest in CI using GitHub Actions?

### ISSUE THREAD

**Issue by matthewfeickert** [madgraph5/madgraph4gpu#30]
Hi. I noticed that at the moment there is no CI system setup for the project to do build tests or metric tests. I realize of course that given the nature of the project and its focus on GPUs that you wouldn't have GPU machines that you can easily run CI on. If there is any interest in using GitHub Actions to setup a CI system though please let me know if I can be of any help with getting things started on that end or answering quetions.

I also wanted to say that it is great to see this project in the first place, and even more so on GitHub, so congrats to the whole dev team and thank you for your great work on this software.

**Comment by roiser** [comment]
Hi @matthewfeickert thanks for your interest. Would you have examples of workflows for github CIs involving GPUs?

**Comment by matthewfeickert** [comment]
> Would you have examples of workflows for github CIs involving GPUs?

As mentioned above, this isn't really a feasible thing to do. You can of course run GitHub Actions on a private runner on a machine that you have access to you, but I would assume that in most instances you want to do benchmarking in a separate workflow than CI.

I guess it depends on what the goal of this particular repo is. Is it a testing grounds for recipes that would be used in future `mg5` work? Or is it meant to be used to develop that new version of the tool? If the latter than CI that can't use GPUs might make sense. If the former, then I can see that you'd be more interested in having performance benchmarking suites that could run automatically on GPU enabled private machines of yours.

**Comment by roiser** [comment]
We want to do both. The repo is primarily meant to develop a GPU enabled version of madgraph, so we need to check correctness with every commit. But we are also interested in the performance as we want to know our speedup factors of workflows over e.g. CPU only versions of the code.
