### ISSUE TITLE
Fix "nprocesses>1" code generation (example: uutt within pptt)

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#343]
Hi @oliviermattelaer as discussed today at the meeting I am assigning this to you.

This is a followup to #337 and to #272. The problem: code generation for pptt now succeeds (after fixing the assert in #337), however the code does not build in the uutt subdirectory, because nprocesses=2 there (#272).

 I checked that the uutt standalone and the uutt within pptt differ in the following way for instance:

```
/data/avalassi/GPU2020/madgraph4gpuX/epochX/cudacpp> diff -r pp_tt.auto/ uu_tt.auto/
...
diff -r pp_tt.auto/SubProcesses/P1_Sigma_sm_uux_ttx/CPPProcess.cc uu_tt.auto/SubProcesses/P1_Sigma_sm_uux_ttx/CPPProcess.cc
...
502c497
<     const int denominators = 36,36; // FIXME: assume process.nprocesses == 1 for the moment (eventually denominators[nprocesses]?)
---
>     const int denominators = 36; // FIXME: assume process.nprocesses == 1 for the moment (eventually denominators[nprocesses]?)
```
From our discussions, I understand that this is because "uutt" within pptt is not only "uu" proper, but also some other combinations of quarks (as you mentioned today, probably it is that u+ubar to t+tbar and ubar+u to t+tbar are not exactly the same?). Anyway, what I mean is that the ggtt within pptt and the ggtt standalone instead are essentially the same code, so it is really the "uutt" part which is different.

As discussed today, this probaby comes from the base python that you developed, rather than from my plugin modifying your python. So best if you take a look. Thanks! Andrea

PS I am instead merging PR #340 that contains ONLY the fix for the assert in #337

**Comment by oliviermattelaer** [comment]
So I confirm that the nprocesses=2 is due here to the symmetry between u u~ process and u~ u.
As it is quite clear from the code below:
```
        calculate_wavefunctions(perm, helicities[ihel]);
        t[0] = matrix_1_uux_ttx();
        // Mirror initial state momenta for mirror process
        perm[0] = 1;
        perm[1] = 0;
        // Calculate wavefunctions
        calculate_wavefunctions(perm, helicities[ihel]);
        // Mirror back
        perm[0] = 0;
        perm[1] = 1;
        // Calculate matrix elements
        t[1] = matrix_1_uux_ttx();
```
 
I will prevent such type of duplication of matrix-element for the gpu plugin (I do not see the point to be honest)

**Comment by valassi** [comment]
Thanks Olivier! I created #360 and assigned it to myself about moving to a more recent launchpad version

**Comment by valassi** [comment]
Just a note, I observed this again while looking at clang-format in #388, but I will ignore it there

**Comment by valassi** [comment]
Reopening. Olivier has fixed this in upstream bazaar, but I need to fix this in the cudacpp plugin.

I have tested that the bazaar "gpu" backend has changed between 270 and 311:
```
diff -r pp_tt.gpu270 pp_tt.gpu311
...
diff -r pp_tt.gpu270/SubProcesses/P1_Sigma_sm_uux_ttx/CPPProcess.cc pp_tt.gpu311/SubProcesses/P1_Sigma_sm_uux_ttx/CPPProcess.cc
3c3
< // MadGraph5_aMC@NLO v. 2.9.5, 2021-08-22
---
> // MadGraph5_aMC@NLO v. 3.3.1_lo_vect, 2022-01-30
297,298c297,298
<     const int nprocesses = 2;  // FIXME: assume process.nprocesses == 1
<     const int denominators[2] = {36, 36}; 
---
>     const int nprocesses = 1;  // FIXME: assume process.nprocesses == 1
>     const int denominators[1] = {36}; 
303a304
> 
345a347
> 
``` 

Note in particular that my plugin produces bad code both with 270 and with 311,
```
const int denominators = 36,36; 
```
The fix is simple, the denominators should become an array and take the number of subprocesses (which is 1 in the new version, but it still remains an array denominators[1], not a scalar denominators).
