### ISSUE TITLE
Use a newer compiler in the CI (gcc10.2 and cuda 11.6, for instance)

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#355]
Hi @hageboeck can you please upgrade the gcc and cuda versions in the CI (and/or tell me how to do that?)

I have added a check for gcc>=9.3 because I had seen that this is what the CI uses on linux, but apparently on MAC it uses an older one?

(Actually, I see MAC probably uses clang13 based on a gcc <9.3 toolkit, I will improve my checks... but it would still be good to have gcc10.2 as native on Linux, and possibly a clang using also a gcc10 toolkit)

What do you think?
Thanks
Andrea

**Comment by valassi** [comment]
I have added a workaround, I do not constrain gcc>=9.3 if gcc is used below clang (#96). So there is no urgency for this.

**Comment by hageboeck** [comment]
It already provides gcc 10.2:
```
$ scl run gcc-toolset-10 "gcc --version"
gcc (GCC) 10.2.1 20201112 (Red Hat 10.2.1-8)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If you really need gcc9, I think we just got the latest that RedHat wanted to give us. I don't know if they managed to bump this up in the mean time. If the need comes back, I can try to recreate the container.
```
$ scl run gcc-toolset-9 "gcc --version"
gcc (GCC) 9.2.1 20191120 (Red Hat 9.2.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Cuda could indeed be upgraded (currently 11.4), but I would postpone this to having a vGPU node on openstack, unless you cannot work with 11.4 for the coming weeks.

**Comment by hageboeck** [comment]
Regarding the Mac, we just use the latest that github gives us, see here:
https://github.com/madgraph5/madgraph4gpu/blob/06522ae596dfb8b2f676563e516c4e244293374c/.github/workflows/c-cpp.yml#L33-L38

As per [Actions docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), that's currently macOS Catalina 10.15. You can force it to use Big Sur if you change this to `macos-11`, but I don't know which kind of compilers that's going to give to you. I'm getting
`gcc --version == clang13`.

**Comment by valassi** [comment]
Thanks to Stephan we are now using cuda12 on alma9 (with native gcc11.3). This can be closed
