### ISSUE TITLE
Fix Mac-specific issues

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#375]
As a part of PR #367 about shared libraries, I added rpath to the executable builds, to make it unnecessary to add LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH). The rpath ORIGIN does not work on Mac, 
```
c++ -o check.exe ./check_sa.o  -ldl -pthread -L../../lib -lmg5amc_common -Wl,-rpath='$ORIGIN/../../lib'   -L../../lib -lmg5amc_cxx
ld: unknown option: -rpath=$ORIGIN/../../lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [check.exe] Error 1
```
I will need to fix that.
https://github.com/madgraph5/madgraph4gpu/runs/5074122375?check_suite_focus=true
https://stackoverflow.com/questions/26280738

En passant I noticed that there are also a few other issues, eg /proc/cpuinfo does not exist on Mac.

I open thic catch-all issues to fix all of these in the various makefiles and scripts (and possibly in code if necessary?)

**Comment by valassi** [comment]
I attempted a patch but this also fails
https://github.com/madgraph5/madgraph4gpu/runs/5077494059?check_suite_focus=true
```
c++ -o check.exe ./check_sa.o  -ldl -pthread -L../../lib -lmg5amc_common -Wl,-rpath='@executable_path/../../lib'   -L../../lib -lmg5amc_cxx
ld: unknown option: -rpath=@executable_path/../../lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [check.exe] Error 1
```

**Comment by valassi** [comment]
Replacing "-rpath=" by "-rpath," makes the build succeed but the runtime fails
https://github.com/madgraph5/madgraph4gpu/runs/5077528086?check_suite_focus=true
```
c++ -o runTest.exe ./CPPProcess.o ./RandomNumberKernels.o ./RamboSamplingKernels.o ./MatrixElementKernels.o ./BridgeKernels.o ./CrossSectionKernels.o ./testxxx.o  ./testmisc.o  ./runTest.o -ldl -pthread -L../../lib -lmg5amc_common -L../../../../../test/googletest/build/lib/ -lgtest -lgtest_main -Wl,-rpath,'@executable_path/../../lib' 
...
./runTest.exe
dyld: Library not loaded: ../lib/libmg5amc_common.so
  Referenced from: /Users/runner/work/madgraph4gpu/madgraph4gpu/epochX/cudacpp/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/./runTest.exe
  Reason: image not found
make: *** [runTest] Abort trap: 6
```
To be debugged

**Comment by valassi** [comment]
I have added a temporary patch, adding back LD_LIBRARY_PATH to the runtime in 'make check', This makes the CI succeed at least. I will add a better patch when I can debug it.
https://github.com/madgraph5/madgraph4gpu/pull/367/commits/1222ac1dc46e747f09898d042be8794e0b2a91d1

**Comment by valassi** [comment]
I have temporarely disabled the build of the Fortran executables on Mac in the CI #376

**Comment by valassi** [comment]
I have reenabled the Mac build of Fortran executables thanks to Stephan's fixes in #377 and #378

**Comment by valassi** [comment]
Fixed the -lgfortran issue by this hack
```
$(fcxx_main): LIBFLAGS += -L$(shell dirname $(shell $(FC) --print-file-name libgfortran.dylib)) # add path to libgfortran on Mac #375
```

**Comment by valassi** [comment]
Many comments about NEON 128bit SIMD on Mac M1 in #221 and in #421

**Comment by valassi** [comment]
Hi @oliviermattelaer, I am working on this now on your M1 node (thanks!), I did see similar issues and here's how I addressed them:

> I still have issue with fortran/mac compilation
> 
> I did change the makefile in two way:
> 
> ```
> FC=gfortran
> CXXFLAGS+=-mmacosx-version-min=10.8 
> ```
> ... 
> Without the CXXFLAGS the code crash like this
> 
> ```
> c++ -o fcheck.exe ./fcheck_sa.o ./fsampler.o -L../../lib -lmg5amc_common -L/usr/local/lib/gcc/x86_64-apple-darwin19/10.2.0/../../..  -Wl,-rpath,'@executable_path/../../lib'   -lgfortran -L../../lib -lmg5amc_gg_ttx_cxx
> ld: warning: ignoring file ./fcheck_sa.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
> ld: warning: ignoring file /usr/local/lib/libgfortran.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
> Undefined symbols for architecture arm64:
>   "_main", referenced from:
>      implicit entry/start for main executable
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [fcheck.exe] Error 1
> ```
> (which actually sounds better)

The problem here is that on your M1 the default gfortran is the one for x86 Intel
```
/usr/local/bin/gfortran --version
GNU Fortran (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Instead I changed this to the experimental version for ARM aarch64
```
/Users/avalassi/bin/gfortran --version
GNU Fortran (GCC) 11.0.0 20201205 (experimental)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
This is from https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11-arm-alpha2

Using this, the code builds fine, and I do not need to change CXXFLAGS as you have done

**Comment by oliviermattelaer** [comment]
Thanks,

The issue is that the optimized for arm compiler is not ready for quadruple precision and therefore can only run LO code.
(sniffff) (at least all the version that I did found --will try yours ;-))

**Comment by valassi** [comment]
I have prepared a WIP PR #425 that is meant to address all of these issues.

**Comment by valassi** [comment]
I am now ready to merge PR #425 that addresses all of these issues essentially. I will close this #375.

@oliviermattelaer  one note about the fortran compiler: it was quite tricky to get the tests to execute correctly using the fortran compiler for ARM installed in a user directory (as I have no root privileges on your node). The main point was that the gfortran library could not be found, an dthen I had to set DYLD_LIBRARY_PATH. An additional compilcation of this was that MacOS SIP (System Integrity Protection) drops DYLD_LIBRARY_PATH in subprocesses like scripts, so I had to work around this. Anyway,. the bottom line is, if you try out that compiler and install the libs in /usr/local/lib with root privileges, this would probably be the best solution. In case, please let me know :-)
