### ISSUE TITLE
Understand why generated code is not relocatabale

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#405]
Reminder for myself: dump here the error I get when not applying the workaround
https://github.com/madgraph5/madgraph4gpu/pull/401/commits/c702cca150c4eeb8462fbbbd057d14b645f326bc

**Comment by valassi** [comment]
This is about the question by @oliviermattelaer in
https://github.com/madgraph5/madgraph4gpu/pull/401#commitcomment-68460953

**Comment by valassi** [comment]
The issue is descibed here
https://github.com/madgraph5/madgraph4gpu/issues/400#issuecomment-1064497219

Reproducer:
- If I build where the code is generated, it builds ok
- If I copy the directory as-is, and I build it from another location, the build fails

**Comment by oliviermattelaer** [comment]
I guess I would need more details since I fail to reproduce the issue...

**Comment by valassi** [comment]
This sounds a bit like #613, but is a different thing. Agree with Olivier, I cannot understand what I meant here. Maybe fixed in between. Close this as unreproducible for now. Will do many more similar tests in #613 anyway....
