### ISSUE TITLE
making cf, denom and tHel "static constexpr" for the abstraction/reference ports

### ISSUE THREAD

**Issue by smithdh** [madgraph5/madgraph4gpu#407]
To allow the alpaka port (based on golden_epochX4 ) to run the gg->ttggg process I found I needed to make the cf[][] array in calculate_wavefunctions static. This is part of a similar change, 3 occurrences of constexpr changed to static constexpr in CPPProcess.cc, that is already present on master. I attach an example diff.

I believe I’ll have to apply this to the alpaka port, so we can run all the processes we want. However it is likely to have some impact on reference performance; e.g. with the plain CUDA gg->ttgg I saw 26% increase in the ME calculation rate on adding static.

Shall we make a new tag, e.g. golden_epochX5, with these changes and use that one as our base for all the ports?

**Comment by smithdh** [comment]
[static-constexpr-diff.txt](https://github.com/madgraph5/madgraph4gpu/files/8350689/static-constexpr-diff.txt)

**Comment by smithdh** [comment]
Hi Andrea,

The steps you outlined (branch from golden_epochX4, commit on branch, and tag) makes sense to me.

Yours,
David

**Comment by valassi** [comment]
Thanks Taylor... hm maybe both make sense? Lets start with a branch now (can be done quick and easy) and think of a more complex cleanup of the repos later on?

**Comment by smithdh** [comment]
Hi. I'm made branch br_golden_epochX4, based on the tag epochX4 tag.

I added the "static constexpr" to the cudacpp plugin so that it generates code for CPPProcress with static constexpr arrays. This is to reflect this change as a new reference.

As we mentioned in yesterday's (4/4/22) meeting, I added in the alpaka plugin under epochX/ by cherry picking the relevant commits from master. The alpaka on the branch does not include the tput/ subdirectory with example generated processes, or diffCode.sh, generateAndCompare.sh, throughputX.sh scripts. These scripts do exist in alpaka on master, as links to files under cudacpp. However as of epochX4 the scripts in cudacpp were not ready to work with alpaka, and I didn't try to disentangle that required changes from other changes.

**Comment by valassi** [comment]
As suggested by @roiser, this old issue can be closed.

Note again that the 25-30% improvement from 'static constexpr' is the same observed for cudacpp in #283. This is even mentioned in the code, eg for ggtt
```
      // The color denominators (initialize all array elements, with ncolor=2)
      // [NB do keep 'static' for these constexpr arrays, see issue #283]
      static constexpr fptype2 denom[ncolor] = { 3, 3 }; // 1-D array[2]
```

Thanks again @smithdh ! Closing
