### ISSUE TITLE
Should we cleanly separate madevent and cudacpp directories or not?

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#413]
Hi @oliviermattelaer, @roiser, all, this is a part of #400 (makefiles for madevent + cudacpp), but I prefer to split it out as a separate question because it is quite an important decision.

The issue is the following: with the mechanism that I think we are currently targeting,
```
output madevent <dir> --vector_size=16 --me_exporter=standalone_cudacpp
```
the code generator is currently generating the usual madevent, and then the cudacpp ON TOP OF THAT. 

This is not even completely precise. because the standalone cudacpp would create a P1 sudirectory with "Sigma_sm" in the name, while as ME exporter that name disappears. See for instance
https://github.com/valassi/madgraph4gpu/tree/v311/epochX/cudacpp/gg_tt/SubProcesses/P1_Sigma_sm_gg_ttx
https://github.com/valassi/madgraph4gpu/tree/v311/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx

Anyway, the point is, a typical madevent+cudacpp directory, such as
https://github.com/valassi/madgraph4gpu/tree/v311/epochX/cudacpp/gg_tt.mad/
now contains these subdirectories, amongst others:
- Source, with madevent Source
- src, with cudacpp src
- Subprocess, with madevent+cudacpp Subprocess SUPERPOSED
- Subprocess/P1_gg_ttx, with madevent+cudacpp SUPERPOSED (as mentioned above, cudacpp is what would be in SubProcesses/P1_Sigma_sm_gg_ttx)

Specifically for issue #400, this means that there are now in SubProcesses/P1_gg_ttx two make-files:
- "makefile" is that from madevent
- "Makefile" is that from cudacpp
I actually like having two sets of make-files. I will expand on this below.

Anyway, the QUESTION I want to ask is the following:
- OPTION 1, do we want to keep it like this, with source files from madevent/fortran and from cudacpp mixed in the same directries?
- OPTION 2, or do we want to actually have cleanly separate directories for madevent and cudacpp source code?...
(And if we go for option 1. do we even want to go one step further and merge Source and src?)

FOR THE MOMENT, my working assumption is to go with option 1. But we should agree on what seems a most reasonable directory structure, eventually.

A related, and similar question, is whether the build products (not only the source files) from madevent and cudacpp whould be in separate directories. For the moment, I am also keeping them all together. The choice also has some non-trivial implications, because for instance whether we need an "include" directory as a result of the cudacpp build (to be used by madevent) or whether this is not needed as the sources are already available, depends on the directory structure. Also the handling of rpath deppnds on the directory structure.

Note that, even in option 1, I do find it quite convenient to have two separate makefiles for madevent and cudacpp. I am adding a few explicit "-f $(THISMK)" to invocations of internal makes, to make this possible, I will most likely:
- keep the madevent "makefile" as main
- rename the cudacpp as "plugin.mk" (to also foresee alpaka etc), and call it from the madevent makefile
- for standalone cudacpp, add a symlink of plugin.mk to Makefile so that one can simply type "make" without "-f", as presently done

Voila, long post, but I found this useful to ask the question. Option one or option two? For the moment I am staying on option 1 for convenience as the code currently works like this. I probably have a slight preference for option2 eventually to have a cleaner separation, but I am not 100% sure, and I would like to discuss with you.

Thanks!
Andrea

**Comment by roiser** [comment]
Hi Andrea , from a software engineering point of view I would suggest to go for option 2, ie. keep the fortran and C++ code separate. This looks cleaner to me and may also be better when looking ahead when we may want to move more stuff from fortran to C++/GPU, but I suppose the final word should be with Olivier, best Stefan

**Comment by valassi** [comment]
Thanks Stefan, I tend to agree, fo rthe eventual solution.

For the very short term (this week), I am keeping option 1. By the way, in this respect, Olivier, why are directory names below SubProcesses different, `ee_mumu.mad/SubProcesses/P1_ll_ll` vs `ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum`? It is especially the "ll_ll" vs "epem_mupmum" that I do not understand (maybe the Sigma_sm is just because it is stanadalone?).

**Comment by valassi** [comment]
Note that makefile and Makefil clash on case-insensitive systems #480

**Comment by valassi** [comment]
I am merging PR #484, where I renamed the cudacpop Makefile as cudacpp.mk to avoid a clash with the madevent makefile on case insensitive systems as suggested by @oliviermattelaer.

Essentially I am keeping option 1 as it works (and maybe this is what Olivier prefers anyway?). Eventually we can move to option 2, or do another type of cleanup. For the moment I am closing this issue.
