### ISSUE TITLE
Are there alphas-dependent parameters (not couplings) in cIPD?

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#437]
Hi @oliviermattelaer this is related to PR #434.

Important to clarify, are there possibly parameters in cIPD (now MZ and mW for eemumu, MT and WT for ggtt) that could depend on alphas? 

I ask because one of the delicate points in the backport is understanding what goes in cipc and cipd. In cipc we used to hav eALL couplings, now I must find a way to put ONLY indepdent couplings. For CIPD it seems to be a subset of parameters anyway, but I cannot judge in advance.

Can you confirm that we will NOT have any parameters that depend on as too? Otherwise, this is another big piece of work...

Thanks!
Andrea

**Comment by oliviermattelaer** [comment]
Hi,

I guess that they are no physics reason to fully prevent such parameter to run.
But YES everything in the code kind of assume that those are not running.

**Comment by valassi** [comment]
Hi Olivier, thanks :-)

Ok lets say, for the moment we assume that this will not happen. If it should happen, we think about it again!

Andrea
