### ISSUE TITLE
Add mixed precision to the CI tests?

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#581]
Hi @hageboeck do you know if we have mixed precision builds in the CI tests? We should add them otherwise. Thanks! Andrea

I guess it is just changing
```
precision: [ d , f ]
```
to `[d,f,m]?

**Comment by hageboeck** [comment]
Hello @valassi,

I don't know what mixed precision is in this context, but you can certainly configure the precision using the list you mention. Whether madgraph knows what to do with an `m` I don't know. 🙂

**Comment by valassi** [comment]
Thanks @hageboeck I enabled it, hoping that madgraph knows what to do with `m` :-)

I disabled epoch1 and epoch2 tests, which were in any case obsolete (and where m would certainly not work)

In https://github.com/madgraph5/madgraph4gpu/pull/582, will be closed automatically when merged
