### ISSUE TITLE
Disabling auto vectorization in ixx/oxx causes a loss of performance

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#727]
Related to #701 and WIP MR #723 and #724.

Disabling auto vectorization in ixx/oxx causes a loss of performance. I had to add this to avoid FPEs in code that seesm to get autovcetorized. But for ggtt this causes a 30% slowdown...

**Comment by valassi** [comment]
I have fixed this issue in MR #723 by moving back to a completely different strategy.

My main issue was the FPEs in #701. This is caused by ixxx/oxxx SIMD implementations where a vector may be divided by another vector where one element is 0.

My previous strategy to fix FPEs in #701 was
- for the problematic SIMD divisions, use explicit loops element by element: when on eelement is 0, do not execute the division
- however, -O3 seems to autovectorize this somehow, so a SIMD vector division where one element is 0 happens anyway and the FPE takes place
- to work around this, I tried to prevenbt autovectorization on these loops, but this is only possible at the function level ie the whole ixx/oxx, and this efffectively disables SIMD for the whole function, which has a big performance hit for simple processes
- I then fixed this by replacing the 0s in the denominators by fake numbers, as those branches are not used anyway... but I was still using explicit loops

My new strategy is the following:
- since in the end the old strategy consists in using dummy denominators, which the compiler autovectorizes into SIMD, then it is just easier to use SIMD directly!
- so in practice I went back to the initial implementation, and just added fake denominators instead of 0s when I know that branch is not taken... this fixes the FPEs #701 but it also recovers the full SIMD performance fixing this #727

cc @roiser @oliviermattelaer @hageboeck 

This will be in MR #723 (still some work to do..)

**Comment by hageboeck** [comment]
> since in the end the old strategy consists in using dummy denominators, which the compiler autovectorizes into SIMD, then it is just easier to use SIMD directly!

Makes sense! :+1:

**Comment by valassi** [comment]
Thanks @hageboeck !

BUT... this thing is driving me nuts. I spent 4 days on this and am not out of it yet. The whole trick was ok on gcc11. But on clang14 I get FPEs again.

(As a reminder, just so that you think I am not wasting time: this is a blocker for pp->ttW, which an ATLAS colleague indicated as a good candidate for CPU-consuming LO production...).

My gut guess is that the clang14 is trying to be smarter than smart, and is able to understand that it can still do the SIMD with division by zero, because it *thinks* that is in fast math and issues no FPEs? 

The only way I could really find out is by doing some nice disassembly (godbolt or the like), but I am not too fluent.

Anyway, I will still try to debug it. This is very complicated because the moment you print something, it changes the code so that it can print out. And similarly the moment you trn on debug mode...

**Comment by oliviermattelaer** [comment]
My suggestion here would then to reintroduce the if statement in the loop.
Since such if statement only occur in initial/final state function and that such function are basically zero time in the total computation. Forbidding SIMD on that part of the code (or code divergence on GPU) is not a problem.
I would like to avoid that you spend four more days on this.

**Comment by valassi** [comment]
Ouff I finally found another exotic solution: the 'volatile' keyword.

My reasoning was, I wanted to make sure I could outsmart the smart compiler and prevent it from doing stupid things.
- I looked at the gcc compiler options and realised this probably had to do with DCE (dead code elimination), https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html, but I could not find an easy way to disable that
- I googled around and found this intresting presentation on DCE (thanks to the author!): https://www.inf.ed.ac.uk/teaching/courses/ct/19-20/slides/llvm-4-deadcode.pdf... this means the volatile keyword, which I had never really investigated
- Indeed, 'volatile' seems to be what I wanted: a way to tell the compiler "hey you, you MUST compute this variable even if you think you can optimize it away"...
- and, it seems to work :-)

**Comment by valassi** [comment]
> My suggestion here would then to reintroduce the if statement in the loop. Since such if statement only occur in initial/final state function and that such function are basically zero time in the total computation. Forbidding SIMD on that part of the code (or code divergence on GPU) is not a problem. I would like to avoid that you spend four more days on this.

Thanks Olivier :-)

The problem was that I DID try with the if statement in the loop, and it did not work.

But I agree with you, at some point we could have disabled SIMD on the whole of ixx/oxx. To do this however the solution was to add back "__attribute__((optimize("no-tree-vectorize")))" on the function declarations.

Anyway! Now this volatile does seem to work... And it is a very powerful tool, I am happy I discovered it!

The MR should be on the way... now I just need to complete code generation, and regenerate all processes...

**Comment by oliviermattelaer** [comment]
Congrats, this is a very nice solution.
Very complex obviously (never hear that keyword before).

Good job.
