### ISSUE TITLE
Why do we need to compile with openmp flag?

### ISSUE THREAD

**Issue by oliviermattelaer** [madgraph5/madgraph4gpu#758]
Should we remove the openmp flag completely?
or have a way to compile with it on request?

I had to change a makefile to compile on my mac (but will likely create issue with the CI)

**Comment by valassi** [comment]
Hi @oliviermattelaer good point.
(Sorry for the delay in replying).

I have implemented a simple mechanism whereby you can disable OpenMP if you externally set OMPFLAGS= as an empoty string

See https://github.com/madgraph5/madgraph4gpu/pull/874/commits/cb67911ccca86144273015c398bd5b1f43367f20

Conversely, if OMPFLAGS is set externally to something else, for the moment I prefer to ignore this and keep control.

**Comment by oliviermattelaer** [comment]
Perfect thanks,

I think that we should have an agreement on how we handle OpenMP by default from the madgraph5 interface.
 (i.e. should I set OMPFLAGS= by default or not, should we have an entry in the run_card to control that /...) 

Cheers,

Olivier

**Comment by valassi** [comment]
> Perfect thanks,
> 
> I think that we should have an agreement on how we handle OpenMP by default from the madgraph5 interface. (i.e. should I set OMPFLAGS= by default or not, should we have an entry in the run_card to control that /...)
> 
> Cheers,
> 
> Olivier

Thanks a lot Olivier! As discussed in #874 (that I just merged), I reopen this so that we can discuss waht to do... assign it also to you so you remember to provide more suggestions

**Comment by oliviermattelaer** [comment]
I wanted to know yours and @roiser opinion

On my side, I would naively move for OMP OFF by default.
For SIMD case, they are no gain to use OMP.
For the GPU case, this is more blurr but the OMP but I also guess that having multi-process is better than OpenMP (helping to overlap cpu/gpu compuation between the thread)

**Comment by roiser** [comment]
Yes, having multiple processes hammering the GPU is better, but I'm not sure its really needed for the real world use case where we can control how many processes we want to run via the mg5_configuration.txt with nb_core. This is also what I partly (re)exercised when doing the A100/H100 comparison (slides on the indico of the last MG5 dev meeting).

**Comment by valassi** [comment]
I think that this is a complex issue that requires tests and optimizations. And the experiments are doing a lot of this on their own (and we may help them). We had introduced OMP because it is a one-liner way to use many threads, then people used it claiming it was our best thing, while it was a 5-minute game. I would disable OMP by default, mainly because it makes debugging easier. Then I would not remove the OMP code, which sometimes may be useful. So yes I vote to disable OMP by default. Let me know, I can implement that.

**Comment by valassi** [comment]
Following yesterday's discussion I changed this: **OpenMP is disabled by default now** in PR #900 (pening Olivier's review).

It is enabled only if USEOPENMP=1. (This internally checks also if the O/S compiler etc allow this)
