### ISSUE TITLE
Delphes with madgraph

### ISSUE THREAD

**Issue by KareemEzzat2727** [madgraph5/madgraph4gpu#763]
when i install Delphes in Madgraph, I get this error 

>> Building libDelphesNoFastJet.so
c++: error: unrecognized command-line option ‘--bindir/../lib/’
make: *** [Makefile:2420: libDelphesNoFastJet.so] Error 1
Error detected during the compilation. Please check the compilation error and run make manually.

can help me please

**Comment by oliviermattelaer** [comment]
Sorry, you asked that question in the wrong repo.

Sorry,
