### ISSUE TITLE
cudacpp.mk should include make_opts

### ISSUE THREAD

**Issue by oliviermattelaer** [madgraph5/madgraph4gpu#787]
The title says it all.
It is fine for the CI/CD, fine on mac but problematic for @valassi. Sorry Andrea, I assign this to you.

**Comment by valassi** [comment]
Thanks Olivier. 

I found the main problem I was having: adding make_opts was breaking the definition of CUDACPP_MAKEFILE. So this was really a bug.

 I fixed this as
```
override CUDACPP_MAKEFILE := $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))
```

What really makes the diffrence here is the ':='. Without that, the expression is evaluated when used, so it points corrrectly to cudacpp.mk before including make_opts, but it was then pointing to ../../Source/make_opts after including make_opts.

The override is kind of optional, it just ensures that the variable cannot be modified from the outside. Just a reminder that this can be used (and is heavily used elsewhere) to encapsulate the internal environment of a makefile.

I will do a few more tests, comparing the build commands with and without make_opts.

If there are issues later on, we can always come back iteratively and fix issues as they appear.

@oliviermattelaer can you in any case make one or two specific examples of which variables you want to take from make_opts? Just to understand better (and for instance remove some overrides elsewhere if we need to inherit your settings, or add overrides if we do not want to inherit them).

Also copying @hageboeck for info.

**Comment by valassi** [comment]
Ah, and I added a protection, as make_opts does not exist in standalone (gg_tt.sa) builds
```
ifneq ($(wildcard ../../Source/make_opts),)
include ../../Source/make_opts
endif
```

**Comment by oliviermattelaer** [comment]
Excellent, perfect andrea, I have made one PR: https://github.com/madgraph5/madgraph4gpu/pull/788
Where I added a new entry in the run_card to pass information to the cudacpp compiler (in that case how to setup FPtype).

**Comment by valassi** [comment]
Thanks Olivier! I checked that, after fixing the cudacpp.mk bug, I now get the same 'make cleanall; make' output with and without make_opts included, so that is good for me. I close this.

**Comment by valassi** [comment]
Just one point on Mac and gfortran: GNU make assumes FC=f77 if FC is not defined. So indeed in my Linux environment I explicitly export FC=gfortran. But I think this is the correct way
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
