### ISSUE TITLE
 Simd for complex numbers (r,r,r, … i,i,i….)

### ISSUE THREAD

**Issue by roiser** [madgraph5/madgraph4gpu#8]
Try to rearrange the real and imaginary parts of the complex numbers in SIMD format, check performance

**Comment by valassi** [comment]
This is addressed in the context of issue #71 and PR #72.

The RRRRIIII memory layout is implemented in https://github.com/madgraph5/madgraph4gpu/blob/5e90bc80cb9a010a8b56e4b0d608704b1c0b4be9/epoch1/cuda/ee_mumu/src/mgOnGpuVectors.h#L35

Closing.
