### ISSUE TITLE
gbases/gspring status

### ISSUE THREAD

**Issue by oliviermattelaer** [madgraph5/madgraph4gpu#81]
Just copy the email of walter here. Such that it will be easier to find back in the long run:

Hi All,

I seemed to have not pushed my changes to gBASES to my git repository and I also seemed to have lost my local copy. However, I can still point you to the original KEK code:

https://xgitlab.cels.anl.gov/whopkins/MadgraphGPU/-/tree/master/gbases_example

The example integrates a simple function: 
https://xgitlab.cels.anl.gov/whopkins/MadgraphGPU/-/blob/master/gbases_example/gBasesFunc.cu

I believe that I replaced the function in this file with a version of the eemumu sigmaKin function. I remember that I couldn't use CPPProcess because the structure of the code was a bit different, requiring me to copy parameters without the class. 

This function is evaluated here: 
https://xgitlab.cels.anl.gov/whopkins/MadgraphGPU/-/blob/master/gbases_example/gBasesCallFunc.cu
but I don't think I modified this. 

This kernel in turn is called by: 
https://xgitlab.cels.anl.gov/whopkins/MadgraphGPU/-/blob/master/gbases_example/gBases.cu
in a somewhat odd way (by an include of a file that calls the kernel). This is also where I copied the parameters of the process to GPU accessible memory. 

I believe that after the grid has been refined, the grid is output as a binary with the following function:
https://xgitlab.cels.anl.gov/whopkins/MadgraphGPU/-/blob/master/gbases_example/gBasesLibrary.cu#L1489 which is called in the main file:
https://xgitlab.cels.anl.gov/whopkins/MadgraphGPU/-/blob/master/gbases_example/gBasesMain.cu#L253

I don't think that the event generation (the accept/reject part, AKA gSPRING) is included anywhere.

I hope this is useful...

**Comment by valassi** [comment]
As suggested by @roiser this can be closed. For the moment we are using madevent. Then if we ever want to go back to gsprings and gbases, this is a good reference and can be reopened.
