### ISSUE TITLE
Develop a better class hierarch separating madevent and standalone in output.py

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#814]
Develop a better class hierarchy separating madeven and standalone in output.py

See Olivier's comment in https://github.com/madgraph5/madgraph4gpu/pull/813#issuecomment-1926456903 and the discussion there.

Assigned mainly on Olivier to define what would be the correct approach here

**Comment by oliviermattelaer** [comment]
So this is now implemented in #813 and waiting for your review.
So I'm closing this.
