### ISSUE TITLE
 Use const/restrict for ME calculation parameters

### ISSUE THREAD

**Issue by roiser** [madgraph5/madgraph4gpu#9]
Done (const/AV), (restrict/SR). Const is useful to have, also for code readability. Restrict does not show any further improvements but includes a small mod (“const &” for complex parameters)

Const changes in eemumu_AV/master. 

Restrict and “const &” in eemumu_auto/restrict 

More consts in eemumu_AV/master (in addition to what is already upstream.

(Partially) DONE, Const moved upstream to MG5 → merge to eemumu_AV

**Comment by valassi** [comment]
For the record, I have tried to add __restrict__ wherever possible to the GLOBAL code before deleting it (issue #7), I saw no improvement. The consts are done.

We might keepp it open in case we split kernels (eg cuda graphs issue #12) and we want to experiment with this. But for the moment I see no advantage (or no change really) in using restrict.

**Comment by hageboeck** [comment]
I played with restrict in roofit, but it has indeed no effect. It's not even C++. It exists in C, and for C++ it's a compiler extension, which seems to be ignored in all practical cases.
Should we close this?

**Comment by roiser** [comment]
Yes the restrict did not show any improvements

**Comment by valassi** [comment]
Just an observation on restrict. I am doing some comparisons of Fortran and C++, and it seems that Fortran is around 30% faster than C++ when we use the most aggressive optimization options in both (essentially, -O3 and -ffast-math). See some discussion in issue #117 and in https://github.com/madgraph5/madgraph4gpu/blob/4728b756c1fbe1ba8427f8e384a57bf24cdbc1a5/epoch1/gridpack/README.md

This 30% is also consistent with earlier observations by @oliviermattelaer in https://indico.cern.ch/event/907278/contributions/3818707/attachments/2020732/3378680/standalone_speed.pdf

I am not exactly measuring the same thing, so maybe actually the C++ code is doing more things than Fortran. And maybe we should not bother about 30% (unless one wants to disassemble in godbolt and have a look...). But I still find it intriguing. If you read some posts about "is fortran faster than c++" (e.g. https://stackoverflow.com/questions/146159), many people indicate aliasing/restrict as an important difference between Fortran and C++. So I would be curious to know if we can still get bits of performance in C++ (and maybe CUDA) with restrict.

Anyway, just some brainstorming...
