### ISSUE TITLE
master_june24: PR 830 was merged still including merge conflicts

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#901]
Another issue introduced in https://github.com/madgraph5/madgraph4gpu/pull/830 and being reviewed in https://github.com/madgraph5/madgraph4gpu/pull/882.

https://github.com/madgraph5/madgraph4gpu/blob/309a48654372cc74a529185b53289a5bf34eeaa4/epochX/cudacpp/gg_tt.mad/SubProcesses/runTest.cc#L233
```

  void runSigmaKin( std::size_t iiter ) override
  {
    constexpr fptype fixedG = 1.2177157847767195; // fixed G for aS=0.118 (hardcoded for now in check_sa.cc, fcheck_sa.f, runTest.cc)
    for( unsigned int i = 0; i < nevt; ++i ) hstGs[i] = fixedG;
    copyDeviceFromHost( devGs, hstGs ); // BUG FIX #566
<<<<<<< HEAD
    MatrixElementKernelDevice mek( devMomenta, devGs, devRndHel, devRndCol, devChannelIds, devMatrixElements, devSelHel, devSelCol, gpublocks, gputhreads );
    if( iiter == 0 ) mek.computeGoodHelicities();
    mek.computeMatrixElements();
||||||| df29acb07
    MatrixElementKernelDevice mek( devMomenta, devGs, devRndHel, devRndCol, devMatrixElements, devSelHel, devSelCol, gpublocks, gputhreads );
    if( iiter == 0 ) mek.computeGoodHelicities();
    constexpr unsigned int channelId = 0; // TEMPORARY? disable multi-channel in runTest.exe #466
    mek.computeMatrixElements( channelId );
=======
    if( iiter == 0 ) pmek->computeGoodHelicities();
    constexpr unsigned int channelId = 0; // TEMPORARY? disable multi-channel in runTest.exe #466
    pmek->computeMatrixElements( channelId );
>>>>>>> upstream/master
    copyHostFromDevice( hstMatrixElements, devMatrixElements );
  }
```

**Comment by valassi** [comment]
See https://github.com/madgraph5/madgraph4gpu/pull/830/files#r1672032901

**Comment by oliviermattelaer** [comment]
Yes sorry for that @roiser and I are using different test method to test the code (more like a "user").

**Comment by valassi** [comment]
> Yes sorry for that @roiser and I are using different test method to test the code (more like a "user").

Thanks Olivier :-)

The points here are two
- it was confusing whether the changes to consider in 830 were only in CODEGEN or also in generated code: I then assumed that I had to look only at the CODEGEN change
- more generally we had agreed long ago that code should be regenerated in PRs when CODEGEN is changed, this was not done (and it may explain why some minor build issues also were not detected by the old CI)

For reference, my very first commit in 882 was precisely the regeneration of all processes with the CODEGEN as-is from 830. This is commit 8e312bc02

Anyway. I am regenerating the code over and over in #882. This can be closed.
