### ISSUE TITLE
build error in runTest with large values of neppR

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#91]
Hi Stephan, just a question: I am doing some tests for vectorization, changing the values of neppR and neppM, sometimes beyond 32. I have seen that runTest has an hardcoded gputhreads of 32, which then fails if neppR is 64 for instance:

```
runTest.cc: In member function ‘virtual void CPUTest_eemumu_Test::TestBody()’:
runTest.cc:282:35: error: static assertion failed: ERROR! #threads/block should be a multiple of neppR
   static_assert( gputhreads%neppR == 0, "ERROR! #threads/block should be a multiple of neppR" );
                  ~~~~~~~~~~~~~~~~~^~~~
runTest.cc:285:35: error: static assertion failed: ERROR! #threads/block should be a multiple of neppM
   static_assert( gputhreads%neppM == 0, "ERROR! #threads/block should be a multiple of neppM" );
                  ~~~~~~~~~~~~~~~~~^~~~
runTest.cc: In lambda function:
```

Can the value be changed to 64 or above, or would this imply recalculating some reference values?

This is a minor issue, I will stay within 32 for the moment (and I most likely do not need to go beyond), but just to know... Thanks!
Andrea

**Comment by hageboeck** [comment]
- It can be changed
- It requires recalculating the reference
but both are easy. I can do it soon.
