### ISSUE TITLE
Move LIMHEL=0 to madgraph4gpu only and add a runcard allowing LIMHEL=0

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#950]
Hi @oliviermattelaer this is a followup to #941 and PR #935. Two points

> You can set limhel to 0 for test if you want but in production this should be the same fortran code/design.

(1) In https://github.com/madgraph5/madgraph4gpu/issues/941#issuecomment-2264800750 you suggest that LIMHEL=0 should not be the default in production cudacpp. Now it is. So it should be changed eventually. I still want to use LIMHEL=0 for all my tests in madgraph4gpu, so I can move that to generateAndCompare.sh for the code generation in the madgraph4gpu repo.

(2) However, I still think that LIMHEL=0 is a useful setting for tests, also for users, when debugging issues (eg the CMS xsec difference). So I suggest adding it as a hidden parameter in the runcards. Objections or other suggestions?

Thanks
Andrea

**Comment by oliviermattelaer** [comment]
Yes make sense to allow to control such parameter via the run_card. Will look at that

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Andrea Valassi ***@***.***>
Sent: Friday, August 2, 2024 6:34:45 PM
To: madgraph5/madgraph4gpu ***@***.***>
Cc: Olivier Mattelaer ***@***.***>; Mention ***@***.***>
Subject: [madgraph5/madgraph4gpu] Move LIMHEL=0 to madgraph4gpu only and add a runcard allowing LIMHEL=0 (Issue #950)


Hi @oliviermattelaer<https://github.com/oliviermattelaer> this is a followup to #941<https://github.com/madgraph5/madgraph4gpu/issues/941> and PR #935<https://github.com/madgraph5/madgraph4gpu/pull/935>. Two points

You can set limhel to 0 for test if you want but in production this should be the same fortran code/design.

(1) In #941 (comment)<https://github.com/madgraph5/madgraph4gpu/issues/941#issuecomment-2264800750> you suggest that LIMHEL=0 should not be the default in production cudacpp. Now it is. So it should be changed eventually. I still want to use LIMHEL=0 for all my tests in madgraph4gpu, so I can move that to generateAndCompare.sh for the code generation in the madgraph4gpu repo.

(2) However, I still think that LIMHEL=0 is a useful setting for tests, also for users, when debugging issues (eg the CMS xsec difference). So I suggest adding it as a hidden parameter in the runcards. Objections or other suggestions?

Thanks
Andrea

**Comment by oliviermattelaer** [comment]
I'm confused: limhel is not set to zero for madevent (at least for the gpucpp branch).
https://github.com/mg5amcnlo/mg5amcnlo/blob/8c70b1ba4c0f01257d8aa2d337fff716f1ef7e55/Template/LO/Source/genps.inc#L33

So either you are confusing with the standalone mode or we are not understanding each other.
But anyway can make sense to control limhel from the run_card

Olivier

**Comment by valassi** [comment]
> I'm confused: limhel is not set to zero for madevent (at least for the gpucpp branch).
> [](https://github.com/mg5amcnlo/mg5amcnlo/blob/8c70b1ba4c0f01257d8aa2d337fff716f1ef7e55/Template/LO/Source/genps.inc#L33)

Hi Olivier, LIMHEL=0 is in the patch
https://github.com/madgraph5/madgraph4gpu/blob/2f76535c41e3efcd065d31d36e356b90fdb9b554/epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/MG5aMC_patches/PROD/patch.common#L11

The fact that LIMHEL=0 for madeven in cudacpp was discussed many times long ago, Examples 
- #564 Allow LIMHEL>0 in cudacpp (using the exact same algorithm as in fortran)
- Also related #630, PR #705, #417, #419

> But anyway can make sense to control limhel from the run_card

Very good :-)

So lets keep this on the todo list

Andrea

**Comment by oliviermattelaer** [comment]
limhel is now controllable within 3.6.0 branch.
Now we need to put back some support on the cudacpp side.

**Comment by valassi** [comment]
Hi Olivier, thanks a lot

> limhel is now controllable within 3.6.0 branch.

Yes this will be merged in #955 (also #986)

> Now we need to put back some support on the cudacpp side.

I have moved this to a separate #988.

What you have done already complets this part ie #950
- we can set limhel in the runcard for fortran
- for cudacpp, tyhe setting of the runcard hardcodes limhel=0 (see https://github.com/madgraph5/madgraph4gpu/commit/df130b07727d2f99bb564c30e39206e152147aa8)

Closing this, thanks to Olivier

**Comment by valassi** [comment]
Reopen and mark that this is actually closed by #992 (which includes #986 which includes #955)
