### ISSUE TITLE
(june24) check if anything needs to be changed in dsample.f in the use of vecsize_used or nb_warp_used

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#983]
Just a reminder for myself from the chat with @oliviermattelaer this afternoon

=> Check if vecsize_used and nb_warp_used are needed in dsample.f

**Comment by valassi** [comment]
Hi @oliviermattelaer I had a look at the two pieces of code above.

My fortran is rusty (and it took me quite some time to understand the logic of the lagorithm), but all in all it looks correct, in both versions?

Rephrasing: *is there something that you think should be changed?*

To be specific: 
- NB_WARP is never used in the algorith, so there is no need for NB_WARP_USED
- The logic which creates a new bunch of events every VECSIZE_USED in the old code remains the same in the new code, so I do not see a problem?

Even more specifically, the magic is here and is the same in old and new code
```
              if (ivec.lt.VECSIZE_USED)then
                cycle
              endif
c             reset variable for the next grid               
              ivec = 0
```
Until ivec<vecsize_used, only the part above is done (one event at a time). When ivec becomes vecsize_used, the part below (where there are vector APIs, with calls for bunches of vecsize_used events) is executed, but at the same time ivec=0 is reset, so that the next DO will initially fill a bunch.

Then in the vector part (the part 'below'), either vector APIs are used, or explicit loops over vecsize_used events. So all looks ok.

One final comment for my own sanity, passcuts takes a vecsize_used parameter but is actually mainly a scalar event by event call. The parameter is passed because on the "first" call there is some update_param for a full bunch of events. This part of the code looks really dangerous to me. There is a mixture of local FIRSTTIME and a common CUTSDONE. What should be a simple "momenta in for one event, falg true/false out for one event" becomes something whose state depends on a common which is initialized and reset not clear where? (That said, I even wonder if I introduced some of this myself 2-3 years ago? I ceratinly added the vecsize_used as a parameter, because previously it was a vecsize_memmax from a parameter... but definitely the mix of scalar and vector behaviour with commons was already there). Maybe this could be reviewed als to make sure there are no bugs?

Voila. My summary: I am unable to see a problem here about a nb_warp_used missing somewhere. So I would merge june24. But please have a look yourself too Olivier.

Thansk!
Andrea

**Comment by oliviermattelaer** [comment]
Ok convincing argument. Well done
Not sure what confuses me, but whatever, the only thing to do is to apologize for the false alarm and to thank you for this super clear argument and for the time that you took on this.

So let me close this issue and let merge the associated PR

**Comment by valassi** [comment]
No need to apologize Olivier, I very much prefer false alarms than missing real issues! Thanks so much to you, let's move on. I will start merging elsewhere...
