### ISSUE TITLE
Permille cross section discrepancy fortran vs cudacpp (gg_tt.mad) after merging june24 and goodhel together

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#991]
VERY BAD. There is a NEW permille cross section discrepancy fortran vs cudacpp after merging june24 and goodhel together.

This is still WIP, but anyway it does not look good.

Note:
- the test was ok (fortran==cudacpp) in both june24 and goodhel branches
- the test only fails when merging the two together (WIP)
- what changes is that the fortran xsec moves, while the cudacpp xsec remains the same
- the numbers of events are the same, so it does not look like a problem generated by the numbers of events? 
- I found this on the very first test I executed, on gg_tt.mad, so I guess other processes may have this too...

**Comment by valassi** [comment]
I vaguely wonder if this is related to https://github.com/mg5amcnlo/mg5amcnlo/pull/120

I had tried to generated code with that 120, and there was only a few lines changing inggtt.mad, but this included some initializations. Maybe the initializations are missing and this will fix it? (HOWEVER june24 tests by themselves were all ok, so this sounds far fetched).

**Comment by oliviermattelaer** [comment]
Can you check at commit https://github.com/madgraph5/madgraph4gpu/pull/992/commits/7d0a553afb140a20173527a2d1537ba397d2e3d3

This was part of the master_goodhel but seems lost in the merging with june24 or something like that.
This part of this branch: master_for360  (which is only two commit in top of your goodhel branch) and the CI are all green in that case. 

If you agree, can you close this thread?

**Comment by valassi** [comment]
Hi @oliviermattelaer I finally checked that this issues is fixed in your #992. I assume that it was fixed by your commit https://github.com/madgraph5/madgraph4gpu/pull/992/commits/7d0a553afb140a20173527a2d1537ba397d2e3d3
